import { C, F } from "./tokens";
const S = {
  app: { fontFamily: F.ui, maxWidth: 600, margin: "0 auto", padding: "0 16px 40px", background: C.white },
  nav: { display: "flex", borderBottom: `1px solid ${C.gray150}`, marginBottom: 20 },
  navBtn: (active, disabled) => ({ flex: 1, padding: "10px 4px", fontSize: 13, fontWeight: 500, border: "none", background: "transparent", cursor: disabled ? "default" : "pointer", color: active ? C.gray900 : C.gray500, borderBottom: active ? `2px solid ${C.gray900}` : "2px solid transparent", opacity: disabled ? 0.35 : 1 }),
  setupGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  setupCard: (c) => ({ border: `1px solid ${C.gray150}`, borderTop: `3px solid ${c}`, borderRadius: 12, padding: 16 }),
  teamLabel: (c) => ({ fontSize: 11, fontWeight: 600, color: c, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }),
  textInput: { width: "100%", padding: "8px 10px", fontSize: 15, fontWeight: 500, border: `1px solid ${C.gray250}`, borderRadius: 8, background: C.gray45, marginBottom: 12, boxSizing: "border-box" },
  textarea: { width: "100%", height: 160, padding: 10, fontSize: 13, fontFamily: F.mono, border: `1px solid ${C.gray250}`, borderRadius: 8, background: C.gray45, resize: "vertical", lineHeight: 1.6, boxSizing: "border-box" },
  hint: { fontSize: 11, color: C.gray400, marginTop: 6 },
  chip: { display: "inline-block", background: C.gray50, border: `1px solid ${C.gray150}`, borderRadius: 20, padding: "3px 10px", fontSize: 12, margin: "3px" },
  chipNum: { fontWeight: 600, color: C.gray500, marginRight: 4 },
  colorRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 12, flexWrap: "wrap" },
  colorSwatch: (c, sel) => ({ width: 26, height: 26, borderRadius: "50%", background: c, border: sel ? `3px solid ${C.gray900}` : `2px solid ${C.gray150}`, cursor: "pointer", flexShrink: 0, boxSizing: "border-box" }),
  colorPickerInput: { width: 32, height: 26, border: `1px solid ${C.gray250}`, borderRadius: 6, cursor: "pointer", padding: 2 },
  startBtn: (disabled) => ({ width: "100%", marginTop: 20, padding: 14, fontSize: 16, fontWeight: 500, background: disabled ? C.gray300 : C.gray900, color: C.white, border: "none", borderRadius: 10, cursor: disabled ? "not-allowed" : "pointer" }),
  stepLabel: { fontSize: 11, fontWeight: 600, color: C.gray500, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 14 },
  teamBtns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 14 },
  teamBigBtn: (c, isHome) => isHome
    ? { padding: "28px 12px", fontWeight: 600, border: `5px solid ${c}`, borderRadius: 14, background: C.white, color: c, cursor: "pointer", textAlign: "center", lineHeight: 1.3, width: "100%", boxSizing: "border-box" }
    : { padding: "28px 12px", fontWeight: 500, border: "none", borderRadius: 14, background: c, color: C.white, cursor: "pointer", textAlign: "center", lineHeight: 1.3, width: "100%" },
  endQtrBtn: (disabled) => ({ width: "100%", padding: 13, fontSize: 14, fontWeight: 500, border: `1px solid ${C.orange210}`, borderRadius: 10, background: disabled ? C.gray50 : C.amber50, color: disabled ? C.gray350 : C.amber800, cursor: disabled ? "default" : "pointer", marginTop: 4, opacity: disabled ? 0.5 : 1 }),
  eventGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(130px, 1fr))", gap: 10 },
  eventBtn: (sel) => ({ padding: "18px 10px", fontSize: 13, fontWeight: 500, border: sel ? `2px solid ${C.gray900}` : `1px solid ${C.gray250}`, borderRadius: 12, background: sel ? C.gray75 : C.white, color: C.gray900, cursor: "pointer", textAlign: "center", width: "100%" }),
  evIcon: { fontSize: 24, display: "block", marginBottom: 6 },
  playerGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))", gap: 10, maxHeight: "calc(100dvh - 260px)", overflowY: "auto" },
  playerBtn: (sel, color, isHome) => ({
    padding: "18px 10px", fontSize: 14, borderRadius: 12, cursor: "pointer", textAlign: "center", width: "100%",
    background: isHome ? (sel ? (color || C.gray650) : C.white) : (color || C.gray650),
    border: isHome
      ? (sel ? `3px solid ${C.white}` : `4px solid ${color || C.gray650}`)
      : (sel ? `3px solid ${C.white}` : "2px solid transparent"),
    outline: sel ? "2px solid " + (color || C.gray650) : "none",
    boxSizing: "border-box",
  }),
  playerNum: (sel, isHome, color) => ({ fontSize: 20, fontWeight: 600, display: "block", color: (isHome && !sel) ? (color || C.gray650) : C.white }),
  playerName: (sel, isHome, color) => ({ fontSize: 12, color: (isHome && !sel) ? C.gray400 : C.whiteA75, marginTop: 3, wordBreak: "break-word" }),
  backBtn: { fontSize: 13, color: C.gray500, background: "none", border: "none", cursor: "pointer", padding: "4px 0", marginBottom: 14 },
  confirmCard: { background: C.gray45, borderRadius: 12, padding: 24, textAlign: "center", marginBottom: 14 },
  confirmBtns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  yesNoRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 10 },
  threeColRow: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, marginTop: 10 },
  btnPrimary: { padding: 13, fontSize: 15, fontWeight: 500, border: "none", borderRadius: 10, background: C.gray900, color: C.white, cursor: "pointer", width: "100%" },
  btnSecondary: { padding: 13, fontSize: 15, fontWeight: 500, border: `1px solid ${C.gray250}`, borderRadius: 10, background: "transparent", color: C.gray900, cursor: "pointer", width: "100%" },
  btnWarning: { padding: 13, fontSize: 15, fontWeight: 500, border: `1px solid ${C.amber400}`, borderRadius: 10, background: C.amber50, color: C.amber800, cursor: "pointer", width: "100%" },
  btnDanger: { padding: 13, fontSize: 15, fontWeight: 500, border: `1px solid ${C.red300}`, borderRadius: 10, background: C.red50, color: C.red600, cursor: "pointer", width: "100%" },
  btnYes: { padding: 13, fontSize: 15, fontWeight: 500, border: "none", borderRadius: 10, background: C.gray900, color: C.white, cursor: "pointer", width: "100%" },
  btnNo: { padding: 13, fontSize: 15, fontWeight: 500, border: `1px solid ${C.gray250}`, borderRadius: 10, background: "transparent", color: C.gray650, cursor: "pointer", width: "100%" },
  qtrPill: { display: "inline-flex", alignItems: "center", gap: 6, background: C.gray50, border: `1px solid ${C.gray150}`, borderRadius: 20, padding: "4px 12px", fontSize: 12, fontWeight: 600, color: C.gray650 },
  scoreHeader: { display: "grid", gridTemplateColumns: "1fr auto 1fr", alignItems: "center", marginBottom: 16, gap: 12 },
  scoreBig: { fontSize: 38, fontWeight: 500, textAlign: "center", letterSpacing: 2 },
  tabsRow: { display: "flex", gap: 8, marginBottom: 14, flexWrap: "wrap" },
  tabBtn: (active) => ({ padding: "6px 14px", fontSize: 13, border: `1px solid ${C.gray250}`, borderRadius: 20, background: active ? C.gray900 : "transparent", color: active ? C.white : C.gray500, cursor: "pointer" }),
  summaryGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: 20 },
  summaryCard: { background: C.gray45, borderRadius: 10, padding: "12px 14px" },
  summaryLabel: { fontSize: 11, color: C.gray500, textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: 8 },
  summaryRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 2 },
  tableWrap: { border: `1px solid ${C.gray150}`, borderRadius: 12, overflow: "hidden", marginBottom: 20 },
  tableTitle: { fontSize: 12, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", color: C.gray500, padding: "10px 14px 8px", borderBottom: `1px solid ${C.gray150}`, background: C.gray30, display: "flex", justifyContent: "space-between", alignItems: "center" },
  table: { width: "100%", fontSize: 13, borderCollapse: "collapse" },
  thLeft: { padding: "8px 14px", textAlign: "left", fontWeight: 600, fontSize: 11, color: C.gray500, textTransform: "uppercase", letterSpacing: "0.04em", borderBottom: `1px solid ${C.gray150}`, background: C.gray50, whiteSpace: "nowrap" },
  th: (sorted) => ({ padding: "8px 8px", textAlign: "right", fontWeight: 600, fontSize: 11, color: sorted ? C.gray900 : C.gray500, textTransform: "uppercase", letterSpacing: "0.04em", borderBottom: `1px solid ${C.gray150}`, background: C.gray50, cursor: "pointer", whiteSpace: "nowrap" }),
  tdLeft: { padding: "9px 14px", borderBottom: `1px solid ${C.gray75}`, color: C.gray900, textAlign: "left", whiteSpace: "nowrap" },
  td: { padding: "9px 8px", borderBottom: `1px solid ${C.gray75}`, color: C.gray900, textAlign: "right" },
  numBadge: { display: "inline-block", width: 24, height: 24, borderRadius: "50%", background: C.gray75, fontSize: 11, fontWeight: 600, textAlign: "center", lineHeight: "24px", marginRight: 6, color: C.gray500 },
  logList: { maxHeight: 380, overflowY: "auto" },
  logGroup: { borderBottom: `1px solid ${C.gray75}` },
  dupeGroup: { borderBottom: `1px solid ${C.amber150}`, background: C.amber25 },
  dupeBadge: { fontSize: 11, background: C.amber100, border: `1px solid ${C.orange300}`, borderRadius: 10, padding: "2px 8px", color: C.amber800, flexShrink: 0, whiteSpace: "nowrap" },
  logGroupMain: { display: "flex", alignItems: "center", gap: 8, padding: "9px 14px 4px", fontSize: 13 },
  logGroupSub: { display: "flex", flexWrap: "wrap", gap: 4, padding: "0 14px 8px 30px" },
  logSubChip: { fontSize: 11, color: C.gray500, background: C.gray50, borderRadius: 10, padding: "2px 8px" },
  logDot: (c) => ({ width: 8, height: 8, borderRadius: "50%", background: c, flexShrink: 0 }),
  qtrDivider: { display: "flex", alignItems: "center", padding: "6px 14px", background: C.gray50, borderBottom: `1px solid ${C.gray150}`, fontSize: 11, fontWeight: 600, color: C.gray500, textTransform: "uppercase", letterSpacing: "0.06em" },
  logActionBtn: (c) => ({ fontSize: 12, background: "none", border: `1px solid ${c || C.gray150}`, borderRadius: 4, padding: "2px 7px", cursor: "pointer", color: c || C.gray500, flexShrink: 0, lineHeight: 1.4 }),
  undoBtn: { fontSize: 11, fontWeight: 700, background: C.red65, border: `1px solid ${C.red300}`, borderRadius: 4, padding: "2px 6px", cursor: "pointer", color: C.red600, flexShrink: 0, letterSpacing: "0.03em" },
  emptyState: { textAlign: "center", padding: "40px 16px", color: C.gray400, fontSize: 14 },
  questionCard: { background: C.gray45, borderRadius: 12, padding: "20px 20px 16px", marginBottom: 14 },
  questionText: { fontSize: 17, fontWeight: 500, textAlign: "center", marginBottom: 4 },
  questionSub: { fontSize: 13, color: C.gray500, textAlign: "center" },
  pendingBubble: (c) => ({ background: C.gray45, borderLeft: `3px solid ${c}`, borderRadius: "0 8px 8px 0", padding: "8px 12px", marginBottom: 12, fontSize: 13, color: C.gray650 }),
  finalBanner: { background: C.gray850, color: C.white, borderRadius: 12, padding: "20px", textAlign: "center", marginBottom: 20 },
  editBanner: { background: C.amber50, border: `1px solid ${C.amber250}`, borderRadius: 8, padding: "8px 14px", marginBottom: 14, fontSize: 13, color: C.amber800, display: "flex", alignItems: "center", gap: 8 },
  timeConfirmBtn: { width: "100%", marginTop: 10, padding: 13, fontSize: 15, fontWeight: 500, border: "none", borderRadius: 10, background: C.gray900, color: C.white, cursor: "pointer" },
  timelineTable: { width: "100%", fontSize: 13, borderCollapse: "collapse" },
  timelineRow: (c) => ({ borderBottom: `1px solid ${C.gray75}`, background: "transparent" }),
};

export default S;