const S = {
  app: { fontFamily: "system-ui, sans-serif", maxWidth: 600, margin: "0 auto", padding: "0 16px 40px", background: "#fff" },
  nav: { display: "flex", borderBottom: "1px solid #e5e5e5", marginBottom: 20 },
  navBtn: (active, disabled) => ({ flex: 1, padding: "10px 4px", fontSize: 13, fontWeight: 500, border: "none", background: "transparent", cursor: disabled ? "default" : "pointer", color: active ? "#111" : "#888", borderBottom: active ? "2px solid #111" : "2px solid transparent", opacity: disabled ? 0.35 : 1 }),
  setupGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  setupCard: (c) => ({ border: "1px solid #e5e5e5", borderTop: `3px solid ${c}`, borderRadius: 12, padding: 16 }),
  teamLabel: (c) => ({ fontSize: 11, fontWeight: 600, color: c, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }),
  textInput: { width: "100%", padding: "8px 10px", fontSize: 15, fontWeight: 500, border: "1px solid #ddd", borderRadius: 8, background: "#f7f7f7", marginBottom: 12, boxSizing: "border-box" },
  textarea: { width: "100%", height: 160, padding: 10, fontSize: 13, fontFamily: "monospace", border: "1px solid #ddd", borderRadius: 8, background: "#f7f7f7", resize: "vertical", lineHeight: 1.6, boxSizing: "border-box" },
  hint: { fontSize: 11, color: "#aaa", marginTop: 6 },
  chip: { display: "inline-block", background: "#f5f5f5", border: "1px solid #e5e5e5", borderRadius: 20, padding: "3px 10px", fontSize: 12, margin: "3px" },
  chipNum: { fontWeight: 600, color: "#888", marginRight: 4 },
  colorRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 12, flexWrap: "wrap" },
  colorSwatch: (c, sel) => ({ width: 26, height: 26, borderRadius: "50%", background: c, border: sel ? "3px solid #111" : "2px solid #e5e5e5", cursor: "pointer", flexShrink: 0, boxSizing: "border-box" }),
  colorPickerInput: { width: 32, height: 26, border: "1px solid #ddd", borderRadius: 6, cursor: "pointer", padding: 2 },
  startBtn: (disabled) => ({ width: "100%", marginTop: 20, padding: 14, fontSize: 16, fontWeight: 500, background: disabled ? "#ccc" : "#111", color: "#fff", border: "none", borderRadius: 10, cursor: disabled ? "not-allowed" : "pointer" }),
  stepLabel: { fontSize: 11, fontWeight: 600, color: "#888", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 14 },
  teamBtns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 14 },
  teamBigBtn: (c, isHome) => isHome
    ? { padding: "28px 12px", fontWeight: 600, border: `5px solid ${c}`, borderRadius: 14, background: "#fff", color: c, cursor: "pointer", textAlign: "center", lineHeight: 1.3, width: "100%", boxSizing: "border-box" }
    : { padding: "28px 12px", fontWeight: 500, border: "none", borderRadius: 14, background: c, color: "#fff", cursor: "pointer", textAlign: "center", lineHeight: 1.3, width: "100%" },
  endQtrBtn: (disabled) => ({ width: "100%", padding: 13, fontSize: 14, fontWeight: 500, border: "1px solid #e0d0b0", borderRadius: 10, background: disabled ? "#f5f5f5" : "#fffbf0", color: disabled ? "#bbb" : "#7a5c00", cursor: disabled ? "default" : "pointer", marginTop: 4, opacity: disabled ? 0.5 : 1 }),
  eventGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(130px, 1fr))", gap: 10 },
  eventBtn: (sel) => ({ padding: "18px 10px", fontSize: 13, fontWeight: 500, border: sel ? "2px solid #111" : "1px solid #ddd", borderRadius: 12, background: sel ? "#f0f0f0" : "#fff", color: "#111", cursor: "pointer", textAlign: "center", width: "100%" }),
  evIcon: { fontSize: 24, display: "block", marginBottom: 6 },
  playerGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))", gap: 10, maxHeight: "calc(100dvh - 260px)", overflowY: "auto" },
  playerBtn: (sel, color, isHome) => ({
    padding: "18px 10px", fontSize: 14, borderRadius: 12, cursor: "pointer", textAlign: "center", width: "100%",
    background: isHome ? (sel ? (color || "#555") : "#fff") : (color || "#555"),
    border: isHome
      ? (sel ? "3px solid #fff" : `4px solid ${color || "#555"}`)
      : (sel ? "3px solid #fff" : "2px solid transparent"),
    outline: sel ? "2px solid " + (color || "#555") : "none",
    boxSizing: "border-box",
  }),
  playerNum: (sel, isHome, color) => ({ fontSize: 20, fontWeight: 600, display: "block", color: (isHome && !sel) ? (color || "#555") : "#fff" }),
  playerName: (sel, isHome, color) => ({ fontSize: 12, color: (isHome && !sel) ? "#aaa" : "rgba(255,255,255,0.75)", marginTop: 3, wordBreak: "break-word" }),
  backBtn: { fontSize: 13, color: "#888", background: "none", border: "none", cursor: "pointer", padding: "4px 0", marginBottom: 14 },
  confirmCard: { background: "#f7f7f7", borderRadius: 12, padding: 24, textAlign: "center", marginBottom: 14 },
  confirmBtns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  yesNoRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 10 },
  threeColRow: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, marginTop: 10 },
  btnPrimary: { padding: 13, fontSize: 15, fontWeight: 500, border: "none", borderRadius: 10, background: "#111", color: "#fff", cursor: "pointer", width: "100%" },
  btnSecondary: { padding: 13, fontSize: 15, fontWeight: 500, border: "1px solid #ddd", borderRadius: 10, background: "transparent", color: "#111", cursor: "pointer", width: "100%" },
  btnWarning: { padding: 13, fontSize: 15, fontWeight: 500, border: "1px solid #e0c060", borderRadius: 10, background: "#fffbf0", color: "#7a5c00", cursor: "pointer", width: "100%" },
  btnDanger: { padding: 13, fontSize: 15, fontWeight: 500, border: "1px solid #f0a0a0", borderRadius: 10, background: "#fff5f5", color: "#c0392b", cursor: "pointer", width: "100%" },
  btnYes: { padding: 13, fontSize: 15, fontWeight: 500, border: "none", borderRadius: 10, background: "#111", color: "#fff", cursor: "pointer", width: "100%" },
  btnNo: { padding: 13, fontSize: 15, fontWeight: 500, border: "1px solid #ddd", borderRadius: 10, background: "transparent", color: "#555", cursor: "pointer", width: "100%" },
  qtrPill: { display: "inline-flex", alignItems: "center", gap: 6, background: "#f5f5f5", border: "1px solid #e5e5e5", borderRadius: 20, padding: "4px 12px", fontSize: 12, fontWeight: 600, color: "#555" },
  scoreHeader: { display: "grid", gridTemplateColumns: "1fr auto 1fr", alignItems: "center", marginBottom: 16, gap: 12 },
  scoreBig: { fontSize: 38, fontWeight: 500, textAlign: "center", letterSpacing: 2 },
  tabsRow: { display: "flex", gap: 8, marginBottom: 14, flexWrap: "wrap" },
  tabBtn: (active) => ({ padding: "6px 14px", fontSize: 13, border: "1px solid #ddd", borderRadius: 20, background: active ? "#111" : "transparent", color: active ? "#fff" : "#888", cursor: "pointer" }),
  summaryGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: 20 },
  summaryCard: { background: "#f7f7f7", borderRadius: 10, padding: "12px 14px" },
  summaryLabel: { fontSize: 11, color: "#888", textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: 8 },
  summaryRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 2 },
  tableWrap: { border: "1px solid #e5e5e5", borderRadius: 12, overflow: "hidden", marginBottom: 20 },
  tableTitle: { fontSize: 12, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", color: "#888", padding: "10px 14px 8px", borderBottom: "1px solid #e5e5e5", background: "#f9f9f9", display: "flex", justifyContent: "space-between", alignItems: "center" },
  table: { width: "100%", fontSize: 13, borderCollapse: "collapse" },
  thLeft: { padding: "8px 14px", textAlign: "left", fontWeight: 600, fontSize: 11, color: "#888", textTransform: "uppercase", letterSpacing: "0.04em", borderBottom: "1px solid #e5e5e5", background: "#f5f5f5", whiteSpace: "nowrap" },
  th: (sorted) => ({ padding: "8px 8px", textAlign: "right", fontWeight: 600, fontSize: 11, color: sorted ? "#111" : "#888", textTransform: "uppercase", letterSpacing: "0.04em", borderBottom: "1px solid #e5e5e5", background: "#f5f5f5", cursor: "pointer", whiteSpace: "nowrap" }),
  tdLeft: { padding: "9px 14px", borderBottom: "1px solid #f0f0f0", color: "#111", textAlign: "left", whiteSpace: "nowrap" },
  td: { padding: "9px 8px", borderBottom: "1px solid #f0f0f0", color: "#111", textAlign: "right" },
  numBadge: { display: "inline-block", width: 24, height: 24, borderRadius: "50%", background: "#f0f0f0", fontSize: 11, fontWeight: 600, textAlign: "center", lineHeight: "24px", marginRight: 6, color: "#888" },
  logList: { maxHeight: 380, overflowY: "auto" },
  logGroup: { borderBottom: "1px solid #f0f0f0" },
  logGroupMain: { display: "flex", alignItems: "center", gap: 8, padding: "9px 14px 4px", fontSize: 13 },
  logGroupSub: { display: "flex", flexWrap: "wrap", gap: 4, padding: "0 14px 8px 30px" },
  logSubChip: { fontSize: 11, color: "#888", background: "#f5f5f5", borderRadius: 10, padding: "2px 8px" },
  logDot: (c) => ({ width: 8, height: 8, borderRadius: "50%", background: c, flexShrink: 0 }),
  qtrDivider: { display: "flex", alignItems: "center", padding: "6px 14px", background: "#f5f5f5", borderBottom: "1px solid #e5e5e5", fontSize: 11, fontWeight: 600, color: "#888", textTransform: "uppercase", letterSpacing: "0.06em" },
  logActionBtn: (c) => ({ fontSize: 12, background: "none", border: `1px solid ${c || "#e5e5e5"}`, borderRadius: 4, padding: "2px 7px", cursor: "pointer", color: c || "#888", flexShrink: 0, lineHeight: 1.4 }),
  undoBtn: { fontSize: 11, fontWeight: 700, background: "#fff0ee", border: "1px solid #f0a0a0", borderRadius: 4, padding: "2px 6px", cursor: "pointer", color: "#c0392b", flexShrink: 0, letterSpacing: "0.03em" },
  emptyState: { textAlign: "center", padding: "40px 16px", color: "#aaa", fontSize: 14 },
  questionCard: { background: "#f7f7f7", borderRadius: 12, padding: "20px 20px 16px", marginBottom: 14 },
  questionText: { fontSize: 17, fontWeight: 500, textAlign: "center", marginBottom: 4 },
  questionSub: { fontSize: 13, color: "#888", textAlign: "center" },
  pendingBubble: (c) => ({ background: "#f7f7f7", borderLeft: `3px solid ${c}`, borderRadius: "0 8px 8px 0", padding: "8px 12px", marginBottom: 12, fontSize: 13, color: "#555" }),
  finalBanner: { background: "#1a1a1a", color: "#fff", borderRadius: 12, padding: "20px", textAlign: "center", marginBottom: 20 },
  editBanner: { background: "#fffbf0", border: "1px solid #e0d0a0", borderRadius: 8, padding: "8px 14px", marginBottom: 14, fontSize: 13, color: "#7a5c00", display: "flex", alignItems: "center", gap: 8 },
  timeConfirmBtn: { width: "100%", marginTop: 10, padding: 13, fontSize: 15, fontWeight: 500, border: "none", borderRadius: 10, background: "#111", color: "#fff", cursor: "pointer" },
  timelineTable: { width: "100%", fontSize: 13, borderCollapse: "collapse" },
  timelineRow: (c) => ({ borderBottom: "1px solid #f0f0f0", background: "transparent" }),
};

export default S;
