import React from 'react';

export default function HeroCard({ game, homeTeam, awayTeam, stats }) {
  const isFinal = game.gameOver;
  const homeScore = stats.home.score;
  const awayScore = stats.away.score;
  const homeColor = homeTeam.color || '#1a6bab';
  const awayColor = awayTeam.color || '#b84e1a';

  // Find Player of the Game (highest points: goals + assists)
  const allPlayers = [
    ...(stats.home.players || []),
    ...(stats.away.players || [])
  ];
  
  const potg = allPlayers.reduce((best, current) => {
    const currentPoints = (current.goals || 0) + (current.assists || 0);
    const bestPoints = best ? (best.goals || 0) + (best.assists || 0) : -1;
    return currentPoints > bestPoints ? current : best;
  }, null);

  return (
    <div id="hero-card-capture" style={{
      width: '1080px',
      height: '1080px',
      backgroundColor: '#f8f9fa',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '40px',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      position: 'relative',
      overflow: 'hidden'
    }}>
      {/* Background accents */}
      <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '20px', backgroundColor: homeColor }} />
      <div style={{ position: 'absolute', bottom: 0, left: 0, width: '100%', height: '20px', backgroundColor: awayColor }} />

      <h1 style={{ fontSize: '48px', color: '#333', marginBottom: '60px', textTransform: 'uppercase', letterSpacing: '4px' }}>
        Game Summary
      </h1>

      <div style={{ display: 'flex', width: '100%', justifyContent: 'space-around', alignItems: 'center', marginBottom: '80px' }}>
        <div style={{ textAlign: 'center', flex: 1 }}>
          <div style={{ fontSize: '120px', fontWeight: 'bold', color: homeColor }}>{homeScore}</div>
          <div style={{ fontSize: '32px', fontWeight: '500' }}>{homeTeam.name}</div>
        </div>
        <div style={{ fontSize: '48px', fontWeight: 'bold', color: '#ccc' }}>VS</div>
        <div style={{ textAlign: 'center', flex: 1 }}>
          <div style={{ fontSize: '120px', fontWeight: 'bold', color: awayColor }}>{awayScore}</div>
          <div style={{ fontSize: '32px', fontWeight: '500' }}>{awayTeam.name}</div>
        </div>
      </div>

      {potg && (
        <div style={{ 
          backgroundColor: '#fff', 
          padding: '40px', 
          borderRadius: '20px', 
          boxShadow: '0 10px 30px rgba(0,0,0,0.05)',
          width: '80%',
          textAlign: 'center'
        }}>
          <h2 style={{ color: '#888', textTransform: 'uppercase', fontSize: '24px', marginBottom: '20px', letterSpacing: '2px' }}>
            Player of the Game
          </h2>
          <div style={{ fontSize: '48px', fontWeight: 'bold', marginBottom: '10px' }}>{potg.name}</div>
          <div style={{ fontSize: '28px', color: '#555' }}>
            {potg.goals} Goals • {potg.assists} Assists • {potg.ground_balls} GBs
          </div>
        </div>
      )}

      <div style={{ position: 'absolute', bottom: '60px', opacity: 0.5, fontSize: '20px' }}>
        Generated by LaxStats
      </div>
    </div>
  );
}